name: Publish
on:
  release:
    types: [published]
jobs:
  publish:
    name: Publish dorai-ui to NPM

    runs-on: ${{ matrix.os }}
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [quality]
    strategy:
      matrix:
        node: ['12.x', '14.x', '15.x']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps and build (with cache)
        - run: yarn install
        - run: yarn build

      - name: Publish to NPM
      - run: yarn semantic-release

        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
