name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: '*'

jobs:
  quality:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [14.x, 16.x]
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Checkout
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Instal Dependencies
        run: yarn install

      - name: Build Packages
        run: yarn build

      - name: Run Tests
        run: yarn test
